### ISSUE TITLE
OSX Pry 0.14.1 Coderay under Ruby 3.0.1 

### ISSUE THREAD

**Issue by DAMisener** [pry/pry-doc#114]
Is this a possible **autoload** related issue? 

**On macOS Catalina Version 10.15.7**

**ruby -v**
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin19]

**pry -v**
Pry version 0.14.1 on Ruby 3.0.1

**gem list coderay**

\*\*\* LOCAL GEMS \*\*\*

coderay (1.1.3)

**Minimal failing test case**

**pry**

[1] pry(main)> **1+1**
```
/users/dm/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/coderay-1.1.3/lib/coderay/tokens_proxy.rb:7:in `<module:CodeRay>': uninitialized constant CodeRay::TokensProxy (NameError)
	from /users/dm/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/coderay-1.1.3/lib/coderay/tokens_proxy.rb:1:in `<top (required)>'
	from <internal:/Users/DM/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/DM/.rbenv/versions/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/DM/work/trunk/lib/require.rb:258:in `require'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/coderay-1.1.3/lib/coderay.rb:169:in `scan'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/syntax_highlighter.rb:14:in `tokenize'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/indent.rb:284:in `tokenize'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/indent.rb:154:in `block in indent'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/indent.rb:146:in `each'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/indent.rb:146:in `indent'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:105:in `read'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:68:in `block in repl'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:67:in `loop'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:67:in `repl'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:38:in `block in start'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/input_lock.rb:61:in `__with_ownership'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/input_lock.rb:78:in `with_ownership'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:38:in `start'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/repl.rb:15:in `start'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/pry_class.rb:188:in `start'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/cli.rb:112:in `start'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/bin/pry:13:in `<top (required)>'
	from /Users/DM/.rbenv/versions/3.0.1/bin/pry:23:in `load'
	from /Users/DM/.rbenv/versions/3.0.1/bin/pry:23:in `<main>'
```

**Possibly unrelated to above issue but suspicious:**

 **pry --no-pager --no-history --no-color**
```
/Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/cli.rb:141:in `block (2 levels) in <top (required)>': undefined method `should_load=' for #<Pry::History:0x00007f876507f8e8 @history=#<Object:0x00007f8765084078>, @history_line_count=0, @file_path=nil, @original_lines=0, @loader=#<Method: Pry::History#read_from_file() /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/history.rb:113>, @saver=#<Method: Pry::History#save_to_file(line) /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/history.rb:122>> (NoMethodError)
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop/option.rb:85:in `call'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop.rb:503:in `process_item'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop.rb:232:in `block in parse!'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop.rb:229:in `each'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop.rb:229:in `each_with_index'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop.rb:229:in `parse!'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/slop.rb:69:in `parse!'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib/pry/cli.rb:68:in `parse_options'
	from /Users/DM/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/bin/pry:12:in `<top (required)>'
	from /Users/DM/.rbenv/versions/3.0.1/bin/pry:23:in `load'
	from /Users/DM/.rbenv/versions/3.0.1/bin/pry:23:in `<main>'
```

**Comment by DAMisener** [comment]
Is there any additional information I can supply?

**Comment by DAMisener** [comment]
Sorry places this issue in the wrong respository.... 

Addressed in full in https://github.com/pry/pry/issues/2218.
User related error :-(
